version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: corprusCheese
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: todo
    ports:
      - '27017:27017'
    volumes:
      - ./config.js:/docker-entrypoint-initdb.d/config.js
      - mongodb:/data/db
volumes:
  mongodb: